name: DO IMAGE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory : /Trial  
      run: docker build .  --file Dockerfile --tag my-image-name:$(date +%s)
