name : Build and publish

on: push

jobs:
  Build:
    runs-on : ubuntu:latest
    
    steps:
    - uses : action/checkout@v3
     
    - name :  Build docker
      working-directory : dotnet
      run : docker build . --file Dockerfile --tag my-app-dotnet 
