name : Lab

on :  push
 #types : [publish]

jobs :
  publish_on_registries:
      runs-on : ubuntu-latest
      permissions:
         packages: write
         contents: read
      steps :
      - name :  Checkout
        uses : actions/checkout@v2
      - name : Login to Dokerhub
        uses : docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
           registry: ghcr.io
           username: ${{github.actor}}
           password : ${{secrets.GITHUB_TOKEN}}
           
      - name : Extract metadata for Docker
        id : meta
        uses: docker/metadata-action@v3
        with:
          images: |
            gamedesignerlee12/liquiid
            ghcr.io/${{ github.repository }}
            
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          file : ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
